# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d8d7a6a854a0b610f04118981dafdfc10c6a04523dd0497ef89ab0b9bb4bb7ab2c625bcf886b8e6fc7be916a1d28ee86c878ad84bfae0389d5e6751e7f725c

test:
  secret_key_base: e0a07c4d94014f202f939f977dedc4498e2e5245866dd56704e8af9979b8f20adb7e7fe75d68e6d161f423b340de58ddf65260c1d3258f30eec015874c34c2fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
